input:
    expression: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/Yan/expression.rds
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: CellGroup
cellGroup: CellGroup
study:
    ID: 2306
    studyAbbr: ground-truth-yan
    longTitle: Single-cell RNA sequencing of human early embryos and embryonic stem cells of 8 development phases
    shortTitle: Yan
debug: FALSE
species: Homo sapiens
