input:
    expression: /research/groups/yu3grp/projects/scRNASeq/yu3grp/qpan/SummerIntern/Y2025/RuilinJiang/Dataset2/02_processedData/PortalInput/expression.rds
    activity:   /research/groups/yu3grp/projects/scRNASeq/yu3grp/qpan/SummerIntern/Y2025/RuilinJiang/Dataset2/02_processedData/PortalInput/activity.rds
    networks:   /research/groups/yu3grp/projects/scRNASeq/yu3grp/qpan/SummerIntern/Y2025/RuilinJiang/Dataset2/02_processedData/PortalInput/networks.txt
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: cell_Type
cellGroup: CellGroup
geneSymbol: GeneSymbol
study:
    ID: 2341
    studyAbbr: liver-cancer2-scRNA-seq
    longTitle: liver-cancer2-scRNA-seq
    shortTitle: liver-cancer2-scRNA-seq
debug: FALSE
species: Homo sapiens

