input:
    expression: /research/groups/yu3grp/projects/scRNASeq/yu3grp/qpan/SummerIntern/Y2025/RuilinJiang/Dataset3/02_processedData/byQPan/Portal_input/expression.rds
    activity:   /research/groups/yu3grp/projects/scRNASeq/yu3grp/qpan/SummerIntern/Y2025/RuilinJiang/Dataset3/02_processedData/byQPan/Portal_input/activity.rds
    networks:   /research/groups/yu3grp/projects/scRNASeq/yu3grp/qpan/SummerIntern/Y2025/RuilinJiang/Dataset3/02_processedData/byQPan/Portal_input/networks.txt
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: cell_type
cellGroup: CellGroup
geneSymbol: GeneSymbol
study:
    ID: 2342
    studyAbbr: liver-cancer3-scRNA-seq
    longTitle: liver-cancer3-scRNA-seq
    shortTitle: liver-cancer3-scRNA-seq
debug: FALSE
species: Homo sapiens

