input:
    expression: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/Covid650k/expression.sparse.rds
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: CellGroup
cellGroup: CellGroup
study:
    ID: 2202
    studyAbbr: benchmark-covid650k-sparse
    longTitle: Single-cell RNA sequencing of the immune response in COVID-19
    shortTitle: Covid650k
debug: FALSE
species: Homo sapiens
