input:
    expression: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/Covid97k/expression.rds
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: CellGroup
cellGroup: CellGroup
study:
    ID: 2316
    studyAbbr: benchmark-covid97k
    longTitle: Single-cell multi-omics analysis of the immune response in COVID-19
    shortTitle: Covid97k
debug: FALSE
species: Homo sapiens
