input:
    expression: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/PBMC20k/expression.rds
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: CellGroup
cellGroup: CellGroup
geneSymbol: gene_name
study:
    ID: 2324
    studyAbbr: pbmc20k
    longTitle: Single-cell RNA sequencing of human peripheral blood mononuclear cells of 10 sorted cell populations
    shortTitle: PBMC20k
debug: FALSE
species: Homo sapiens
