input:
    expression: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/Tregs/expression.rds
    activity:   /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/Tregs/activity.rds
    networks:   /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/Studies/Tregs/networks.txt
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: celltype
cellGroup: CellGroup
cellID: cellID
geneSymbol: GeneSymbol
study:
    ID: 2326
    studyAbbr: tregs
    longTitle: Single-cell RNA sequencing of regulatory T cells (Tregs) of 4 mouse non-lymphoid tissues
    shortTitle: Tregs
debug: FALSE
species: Mus musculus
