input:
    expression: /research_jude/rgs01_jude/groups/yu3grp/projects/RelapseALL/yu3grp/XuYang/ATRT/Portal/scMINER/ATRT/output/ATRT_expression.eset.rds
    activity:   /research_jude/rgs01_jude/groups/yu3grp/projects/RelapseALL/yu3grp/XuYang/ATRT/Portal/scMINER/ATRT/output/ATRT_T_activity.eset.rds
    networks:   /research_jude/rgs01_jude/groups/yu3grp/projects/RelapseALL/yu3grp/XuYang/ATRT/Portal/scMINER/ATRT/output/network.txt
output: /research_jude/rgs01_jude/groups/yu3grp/projects/software_JY/yu3grp/yulab_apps/scMINER/scMINER_Portal/scMINERViewerMetrics
cellType: annotation_subtype
cellGroup: annotation_subtype
cellID: CellID
geneSymbol: geneSymbol
study:
    ID: 2333
    studyAbbr: ATRT
    longTitle: An atypical teratoid rhabdoid tumor (ATRT) is a very rare, aggressive tumor of the central nervous system, occurring mostly in the cerebellum.
    shortTitle: ATRT
debug: FALSE
species: Homo sapiens
